### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [hyotang666/vivid-diff#1]
Building with SBCL 2.2.4 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id dae6a74dbeb20b4b296e2f8072b4176223b65ab7

*vivid-diff.test* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: The variable ECLECTOR.READER::*LABELS* is unbound.(in form starting at line: 168, column: 0, position: 3809)
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C58003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "vivid-diff.test" "vivid-diff">

```

[Full log here](http://report.quicklisp.org/2022-06-21/failure-report/vivid-diff.html)

**Comment by hyotang666** [comment]
Thank you for reporting.
This is related to jingoh.reader and the bug is fixed in jingoh.reader side.
